subugoe_text_api_item_page:
    path:      "text-api/{manifest}/{item}/{revision}/item.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\TextApiController::item, "revision":"latest" }

subugoe_text_api_item_full:
    path:      "text-api/{id}/{revision}/full.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\TextApiController::full, "revision":"0.0.2" }

#subugoe_text_api_collection_manifest:
#    path:      "text-api/{collection}/{manifest}/manifest.json"
#    methods:  "GET"
#    defaults: { _controller: Subugoe\TextApiBundle\Controller\TextApiController::manifest }

subugoe_text_api_manifest:
    path:      "text-api/{manifest}/manifest.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\TextApiController::manifest }


subugoe_text_api_content:
    path:      "text-api/content/{type}/{id}.html"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\TextApiController::content }


subugoe_text_api_annotation_collection_for_collection:
    path:      "text-api/{collection}/annotationCollection.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\TextApiController::annotationCollection }

subugoe_text_api_annotation_collection_for_manifest:
    path:      "text-api/{manifest}/annotationCollection.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\AnnotationApiController::collectionForManifest }

subugoe_text_api_annotation_collection_for_item:
    path:      "text-api/{manifest}/{item}/{revision}/annotationCollection.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\AnnotationApiController::annotationCollection }



subugoe_text_api_page_annotation_collection:
    path:      "text-api/{id}/{page}/annotationCollection.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\AnnotationApiController::pageAnnotationCollection }

subugoe_text_api_annotation_collection:
    path:      "text-api/{id}/annotationCollection.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\AnnotationApiController::annotationCollection }

subugoe_text_api_annotation_page:
    path:      "text-api/{manifest}/{item}/annotationPage.json"
    methods:  "GET"
    defaults: { _controller: Subugoe\TextApiBundle\Controller\AnnotationApiController::annotationPage }
