services:
  subugoe_text_api.text_api_service:
    class:      Subugoe\TextApiBundle\Service\TextApiService
    arguments: [ "@router", "@parameter_bag"]

  subugoe_text_api.translator:
    class: Subugoe\TextApiBundle\Translator\SubugoeTranslator

